-- MySQL Script generated by MySQL Workbench
-- Mon Jun  3 23:42:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`instituto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instituto` (
  `idInstituto` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeInstituto` VARCHAR(45) NOT NULL,
  `cidadeInstituto` VARCHAR(45) NOT NULL,
  `cursoInstituto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idInstituto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeUsuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `sexo` TINYINT(1) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`personagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personagem` (
  `idPersonagem` INT(11) NOT NULL AUTO_INCREMENT,
  `nomePersonagem` VARCHAR(45) NOT NULL,
  `corpoPersonagem` VARCHAR(50) NOT NULL,
  `idadePersonagem` INT NOT NULL,
  `usuario_idUsuario` INT(11),
  PRIMARY KEY (`idPersonagem`),
  INDEX `fk_personagem_usuario_idx` (`usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_personagem_usuario`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`instituto_has_personagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instituto_has_personagem` (
  `personagem_idInstituto` INT(11) NOT NULL,
  `instituto_idPersonagem` INT(11) NOT NULL,
  PRIMARY KEY (`personagem_idInstituto`, `instituto_idPersonagem`),
  INDEX `fk_instituto_has_personagem_personagem1_idx` (`instituto_idPersonagem` ASC) VISIBLE,
  INDEX `fk_instituto_has_personagem_instituto1_idx` (`personagem_idInstituto` ASC) VISIBLE,
  CONSTRAINT `fk_instituto_has_personagem_instituto1`
    FOREIGN KEY (`personagem_idInstituto`)
    REFERENCES `mydb`.`instituto` (`idInstituto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_instituto_has_personagem_personagem1`
    FOREIGN KEY (`instituto_idPersonagem`)
    REFERENCES `mydb`.`personagem` (`idPersonagem`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`objeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`objeto` (
  `idObjeto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `objeto_idPersonagem` INT(11),
  PRIMARY KEY (`idObjeto`),
  INDEX `fk_objeto_personagem1_idx` (`objeto_idPersonagem` ASC) VISIBLE,
  CONSTRAINT `fk_objeto_personagem1`
    FOREIGN KEY (`objeto_idPersonagem`)
    REFERENCES `mydb`.`personagem` (`idPersonagem`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
