-- MySQL Script generated by MySQL Workbench
-- Wed Jun  5 19:00:20 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

drop database if exists mydb;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`corpo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`corpo` (
  `idCorpo` INT(11) NOT NULL AUTO_INCREMENT,
  `numeroOrdem` INT NOT NULL,
  PRIMARY KEY (`idCorpo`),
  UNIQUE INDEX `idCorpo_UNIQUE` (`idCorpo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`instituto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instituto` (
  `idInstituto` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeInstituto` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `cursoInstituto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idInstituto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeUsuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`personagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personagem` (
  `idPersonagem` INT(11) NOT NULL AUTO_INCREMENT,
  `nomePersonagem` VARCHAR(45) NOT NULL,
  `idadePersonagem` INT NOT NULL,
  `usuario_idUsuario` INT(11) NOT NULL,
  `corpo_idCorpo` INT(11),
  PRIMARY KEY (`idPersonagem`),
  INDEX `fk_personagem_usuario1_idx` (`usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_personagem_corpo1_idx` (`corpo_idCorpo` ASC) VISIBLE,
  CONSTRAINT `fk_personagem_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personagem_corpo1`
    FOREIGN KEY (`corpo_idCorpo`)
    REFERENCES `mydb`.`corpo` (`idCorpo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`objeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`objeto` (
  `idObjeto` INT NOT NULL AUTO_INCREMENT,
  `nomeObjeto` VARCHAR(45) NOT NULL,
  `personagem_idPersonagem` INT(11) NOT NULL,
  PRIMARY KEY (`idObjeto`),
  INDEX `fk_objeto_personagem_idx` (`personagem_idPersonagem` ASC) VISIBLE,
  CONSTRAINT `fk_objeto_personagem`
    FOREIGN KEY (`personagem_idPersonagem`)
    REFERENCES `mydb`.`personagem` (`idPersonagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instituto_has_personagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instituto_has_personagem` (
  `instituto_idInstituto` INT(11),
  `personagem_idPersonagem` INT(11),
  PRIMARY KEY (`instituto_idInstituto`, `personagem_idPersonagem`),
  INDEX `fk_instituto_has_personagem_personagem1_idx` (`personagem_idPersonagem` ASC) VISIBLE,
  INDEX `fk_instituto_has_personagem_instituto1_idx` (`instituto_idInstituto` ASC) VISIBLE,
  CONSTRAINT `fk_instituto_has_personagem_instituto1`
    FOREIGN KEY (`instituto_idInstituto`)
    REFERENCES `mydb`.`instituto` (`idInstituto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_instituto_has_personagem_personagem1`
    FOREIGN KEY (`personagem_idPersonagem`)
    REFERENCES `mydb`.`personagem` (`idPersonagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
