/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import com.sun.jmx.snmp.UserAcl;
import java.awt.CardLayout;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import projeto_java_bd.Corpo;
import projeto_java_bd.Personagem;
import projeto_java_bd.Usuario;

/**
 *
 * @author Henrique Alves
 */
public class TelaMostrar extends javax.swing.JFrame {

    private CardLayout cardLayout;
    private int contador = 0;
    private List<Corpo> listaCorpos = new ArrayList<>();
    Personagem p = new Personagem();

        /**
     * Creates new form TelaMostrar
     */
    public TelaMostrar(Personagem personagem) {
        initComponents();
        this.p = personagem;
        initImage();
    }
    
    
    void initImage(){    
            
        String[] filesName = {"#1.png","#2.png","#3.png","#4.png","#5.png","#6.png",
        "#7.png","#8.png","#9.png","#10.png","#11.png","#12.png","#13.png",
        "#14.png","#15.png","#16.png","#17.png","#18.png","#19.png","#20.png",
        "#21.png","#22.png","#23.png","#24.png","#25.png",
        "#26.png","#27.png","#28.png","#29.png","#30.png","#31.png",
        "#32.png"};
        
        for(String s : filesName){
            
            Icon icon = new ImageIcon("src/img/"+s);
            JLabel label = new JLabel(icon);
            
            Corpo corpo = new Corpo();
            // adicionar informações ao corpo
            
            listaCorpos.add(corpo);
            
            personagem.add(label);
        }
        //create layout
        cardLayout=new CardLayout();
        personagem.setLayout(cardLayout);
        
        for (int i = 0; i < listaCorpos.size(); i++) {
            cardLayout.next(personagem);
            
        }
      
        int a = p.buscarPersonagem(p);
        
        for (int i = 0; i < a-1; i++) {
            cardLayout.next(personagem);
            
        }
       
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltar = new javax.swing.JButton();
        personagem = new javax.swing.JPanel();
        NomePer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        voltar.setText("voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout personagemLayout = new javax.swing.GroupLayout(personagem);
        personagem.setLayout(personagemLayout);
        personagemLayout.setHorizontalGroup(
            personagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
        );
        personagemLayout.setVerticalGroup(
            personagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );

        NomePer.setText("aa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(personagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(voltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(NomePer)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(NomePer)
                        .addGap(172, 172, 172)
                        .addComponent(voltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(personagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        TelaInicial1 t1 = new TelaInicial1(WIDTH);
        t1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Personagem p = new Personagem();
                new TelaMostrar(p).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NomePer;
    private javax.swing.JPanel personagem;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables

}
